name: php-action Test Docker Build Action
description: Github Actions and Docker test project.

inputs:
  php_version:
    description: The version of PHP to use
    default: latest
    required: false

  name:
    description: Name to greet, "Hello, World!" style
    default: World
    required: false

runs:
  using: "composite"
  steps:
    - env:
        ACTION_PHP_VERSION: ${{ inputs.php_version }}
        ACTION_NAME: ${{ inputs.name }}
        ACTION_TOKEN: ${{ github.token }}

      id: runner
      run: ${{ github.action_path }}/docker-build.bash \
        && ${{ github.action_path }}/greet.bash
      shell: bash

branding:
  icon: anchor
  color: blue
